# Generated by Django 5.2.5 on 2025-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Необязательное поле. Введите Ваше имя', max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Необязательное поле. Введите Вашу фамилию', max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
