# Generated by Django 5.2.5 on 2025-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст статьи', verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для превью статьи', null=True, upload_to='media/', verbose_name='Превью')),
                ('is_published', models.BooleanField(default=False, help_text='Признак публикации статьи', verbose_name='Опубликована?')),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['title', 'view_count', 'created_at'],
            },
        ),
    ]
